---

- hosts: servers

  vars:
    provincias_panama: ["Bocas del Toro", "Coclé", "Colón", "Chiriqui", "Darién", "Herrera", "Los Santos", "Panamá", "Veraguas" , "Panamá Oeste"]

  tasks:
    - name: Uso de arreglos
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ provincias_panama }}"
